import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Trash2, Search, Settings, PlusCircle } from "lucide-react";

export default function TaskPlatform() {
  const [tasks, setTasks] = useState([]);
  const [newTask, setNewTask] = useState("");
  const [search, setSearch] = useState("");
  const [selectedDay, setSelectedDay] = useState("hoje");

  const addTask = (day) => {
    if (newTask.trim() !== "") {
      setTasks([...tasks, { id: Date.now(), text: newTask, day }]);
      setNewTask("");
    }
  };

  const removeTask = (id) => {
    setTasks(tasks.filter(task => task.id !== id));
  };

  const filteredTasks = tasks.filter(task => task.day === selectedDay);

  return (
    <div className="max-w-md mx-auto mt-10 p-4 border rounded-lg shadow-lg">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-bold">Gerenciamento de Tarefas</h2>
        <div className="flex gap-2">
          <Button variant="ghost">
            <Settings className="w-6 h-6" />
          </Button>
        </div>
      </div>
      
      <Card className="mb-4 p-4">
        <CardContent>
          <h3 className="font-semibold">Adicionar Tarefas</h3>
          <Input
            value={newTask}
            onChange={(e) => setNewTask(e.target.value)}
            placeholder="Digite uma nova tarefa"
            className="mb-2"
          />
          <Button onClick={() => addTask(selectedDay)} className="mt-2 flex items-center">
            <PlusCircle className="w-5 h-5 mr-2" /> Adicionar
          </Button>
        </CardContent>
      </Card>
      
      <p className="text-sm text-gray-600 mb-2">Use esta plataforma para organizar suas tarefas diárias.</p>
      
      <div className="flex gap-2 mb-4">
        <Button onClick={() => setSelectedDay("hoje")} variant={selectedDay === "hoje" ? "default" : "outline"}>Hoje</Button>
        <Button onClick={() => setSelectedDay("ontem")} variant={selectedDay === "ontem" ? "default" : "outline"}>Ontem</Button>
        <Button onClick={() => setSelectedDay("amanha")} variant={selectedDay === "amanha" ? "default" : "outline"}>Amanhã</Button>
      </div>
      
      <div className="mb-4">
        <h3 className="font-semibold">Buscar Tarefa</h3>
        <Input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Digite para buscar"
          className="mb-2"
        />
      </div>
      
      <Card className="mb-4">
        <CardContent>
          <h3 className="font-semibold">Tarefas Agendadas</h3>
          <ul>
            {filteredTasks.filter(task => task.text.toLowerCase().includes(search.toLowerCase())).map((task) => (
              <li key={task.id} className="flex justify-between items-center p-2 border-b">
                {task.text}
                <Button variant="ghost" onClick={() => removeTask(task.id)}>
                  <Trash2 className="w-4 h-4 text-red-500" />
                </Button>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}
